### ISSUE TITLE
Не выкидывается исключение IllegalArgumentException, если начальный баланс отрицательный

### ISSUE THREAD

**Issue by xamelion098** [xamelion098/TeamProject#1]
# Описание
Если начальный баланс отрицательное число, должно выкидываться исключение IllegalArgumentException "Начальный баланс не может быть отрицательным"

# Локализация дефекта
https://github.com/xamelion098/TeamProject/blob/fc12d7aa17dff327df17febcb1157d32dd40ed03/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19 ;

# Шаги воспроизведения 
1. Открыть код программы в IDEA;
2. Создать тест для объекта CreditAccount с значениями initialBalance -3000, creditLimit 5000 , rate 15;
3. Запустить тест;
4. Увидим ошибку в консоли;
*Ожидаемый результат* Выкидывается исключение IllegalArgumentException Начальный баланс не может быть отрицательным
*Фактический результат* Не выкидывается исключение IllegalArgumentException Начальный баланс не может быть отрицательным
# Скриншот
<img width="959" alt="image" src="https://github.com/user-attachments/assets/947cbfeb-8e0c-4344-aabd-409338832739">

# Окружение 

Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA 2024.2.1 (Community Edition)
Java: OpenJDK 11

**Comment by Ka2sik** [comment]
Fixed
