### ISSUE TITLE
Не выкидывается исключение IllegalArgumentException, если кредитный лимит отрицательный

### ISSUE THREAD

**Issue by xamelion098** [xamelion098/TeamProject#2]
# Описание
Если кредитный лимит отрицательное число, должно выкидываться исключение IllegalArgumentException "Кредитный лимит не может быть отрицательным"

# Локализация дефекта
 https://github.com/xamelion098/TeamProject/blob/fc12d7aa17dff327df17febcb1157d32dd40ed03/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L43 ;

# Шаги воспроизведения 
1. Открыть код программы в IDEA;
2. Создать тест для объекта CreditAccount с значениями initialBalance 0, creditLimit -5000 , rate 15;
3. Запустить тест;
4. Увидим ошибку в консоли;
*Ожидаемый результат* Выкидывается исключение IllegalArgumentException "Кредитный лимит не может быть отрицательным"
*Фактический результат* Не выкидывается исключение IllegalArgumentException "Кредитный лимит не может быть отрицательным"
# Скриншот
<img width="959" alt="image" src="https://github.com/user-attachments/assets/de87e7ee-9cb2-40af-92b4-ec17a3ba3bff">

# Окружение 

Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA 2024.2.1 (Community Edition)
Java: OpenJDK 11

**Comment by Ka2sik** [comment]
Fixed
