### ISSUE TITLE
Некорректно рассчитывается баланс счета если остаток  = 0

### ISSUE THREAD

**Issue by xamelion098** [xamelion098/TeamProject#4]
# Описание
Если сумма покупки равна балансу карты, остаток на счете должен быть равен 0.

# Локализация дефекта
 https://github.com/xamelion098/TeamProject/blob/fc12d7aa17dff327df17febcb1157d32dd40ed03/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40 ;

# Шаги воспроизведения 
1. Открыть код программы в IDEA;
2. Создать тест для объекта CreditAccount с значениями initialBalance 3000, creditLimit 5000 , rate 15, amount 3000
3. Запустить тест;
4. Увидим ошибку в консоли;
*Ожидаемый результат*  Ожидаемый баланс - 0;
*Фактический результат* Фактический баланс - -3000
# Скриншот
<img width="959" alt="image" src="https://github.com/user-attachments/assets/2012c388-2b39-4944-b7f6-46c0794ced35">

# Окружение 

Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA 2024.2.1 (Community Edition)
Java: OpenJDK 11

**Comment by Ka2sik** [comment]
Fixed
