### ISSUE TITLE
Некорректно рассчитывается кредитный процент на положительный баланс.

### ISSUE THREAD

**Issue by xamelion098** [xamelion098/TeamProject#7]
# Описание
Некорректно рассчитывается кредитный процент при положительном балансе счёта.
# Локализация дефекта
 https://github.com/xamelion098/TeamProject/blob/fc12d7aa17dff327df17febcb1157d32dd40ed03/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82 ;

# Шаги воспроизведения 
1. Открыть код программы в IDEA;
2. Создать тест для объекта CreditAccount с значениями initialBalance 3000, creditLimit 5000 , rate 15, amount 1000
3. Запустить тест;
4. Увидим ошибку в консоли;
*Ожидаемый результат*  Ожидаемые проценты по кредиту - 0;
*Фактический результат* Фактические проценты по кредиту - -150
# Скриншот
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d88c6241-4b7c-449c-a995-73aa1172654e">

# Окружение 

Операционная система: Windows 11 Pro
IDE: IntelliJ IDEA 2024.2.1 (Community Edition)
Java: OpenJDK 11

**Comment by Ka2sik** [comment]
Fixed
